-- Add athlete profile fields
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS experience_level TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS weight_kg REAL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS years_training INTEGER;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS ironman_finishes INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS weekly_hours REAL;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS next_race_name TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS next_race_date TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS health_notes TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS notes TEXT;
